import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'package:provider/provider.dart';
import '../config/theme.dart';
import '../config/constants.dart';
import '../config/routes.dart';
import '../models/user_model.dart';
import '../providers/auth_provider.dart';
import '../providers/location_provider.dart';
import '../providers/agent_provider.dart';
import '../models/danger_zone.dart';
import '../services/motion_detection_service.dart';
import '../services/audio_detection_service.dart';
import '../services/voice_detection_service.dart';
import '../screens/map_screen.dart';
import '../screens/alert_screen.dart';
import '../screens/profile_screen.dart';
import '../screens/auto_sos_screen.dart';
import '../screens/responder_alert_screen.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import '../services/nearby_alert_service.dart';
import 'dart:async';
import 'package:flutter_background_service/flutter_background_service.dart';
import '../models/alert_model.dart';
import '../services/notification_service.dart';

class HomeDashboard extends StatefulWidget {
  const HomeDashboard({super.key});

  @override
  State<HomeDashboard> createState() => _HomeDashboardState();
}

class _HomeDashboardState extends State<HomeDashboard> {
  int _currentIndex = 0;
  StreamSubscription? _sosSubscription;
  final NearbyAlertService _nearbyService = NearbyAlertService();
  final Set<String> _activeAlertPopups = {}; // Tracks which alerts showed a popup

  final List<Widget> _screens = [
    const _HomeContent(),
    const MapScreen(),
    const AlertScreen(),
    const ProfileScreen(),
  ];

  @override
  void initState() {
    super.initState();
    
    // ── Pre-initialize Discovery ──
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      final loc = Provider.of<LocationProvider>(context, listen: false);
      final auth = Provider.of<AuthProvider>(context, listen: false);
      final notify = NotificationService();
      
      // 1. Initialize GPS & Notifications
      await loc.initialize();
      await notify.initialize();
      
      // 2. Start Low-Power Tracking for Discovery
      // (This ensures responder always has coords for SOS check)
      if (loc.isTracking == false) {
        print('[SOS] Starting Discovery Tracking...');
        loc.startTracking();
      }

      // Start motion detection automatically
      final motion = Provider.of<MotionDetectionService>(context, listen: false);
      motion.onDangerDetected = (event) {
        if (mounted) {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (_) => AutoSOSScreen(motionEvent: event)),
          );
        }
      };
      motion.startMonitoring();

      final audio = Provider.of<AudioDetectionService>(context, listen: false);
      audio.onDangerDetected = (event, db) {
        if (mounted) {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (_) => AutoSOSScreen(audioEvent: event)),
          );
        }
      };

      final voice = Provider.of<VoiceDetectionService>(context, listen: false);
      voice.onDangerDetected = (event, keyword) {
        if (mounted) {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (_) => AutoSOSScreen(voiceEvent: event)),
          );
        }
      };

      // ── Reliable Nearby SOS Listener (Firestore Stream) ──
      _sosSubscription = _nearbyService.getActiveAlertsStream().listen((alerts) {
        if (!mounted) return;
        
        final loc = Provider.of<LocationProvider>(context, listen: false);
        final auth = Provider.of<AuthProvider>(context, listen: false);
        final notify = NotificationService();
        
        if (auth.user == null) return;
        
        if (loc.latitude == null) {
          print('[SOS Listener] Warning: Responder location is NULL. Delaying check...');
          return;
        }

        print('[SOS Listener] Heartbeat: Checking ${alerts.length} active alerts...');

        // Clean up resolved alerts from our popup set
        final currentAliveAlertIds = alerts.map((a) => a.alertId).toSet();
        _activeAlertPopups.removeWhere((id) => !currentAliveAlertIds.contains(id));

        final currentUserId = auth.user?.id;
        
        for (var alert in alerts) {
          // Hard-block alerts generated by THIS exact phone session
          if (NearbyAlertService.locallyGeneratedAlerts.contains(alert.alertId)) {
             print('[SOS Listener] Skipping alert ${alert.alertId}: This phone generated it.');
             continue;
          }
          
          // Check if I am the victim (Fallback logic)
          if (currentUserId != null && alert.userId == currentUserId) {
            print('[SOS Listener] Skipping alert ${alert.alertId}: I am the victim.');
            continue;
          }
          
          // Check if I am within 50,000 km (massively expanded for emulator testing)
          double distance = loc.distanceTo(alert.latitude, alert.longitude);
          print('==================================================');
          print('[SOS Listener] NEW ALERT DETECTED: ${alert.alertId}');
          print('[SOS Listener] Alert User: ${alert.userId} | My User: $currentUserId');
          print('[SOS Listener] Distance: ${distance.toInt()}m');
          
          if (distance <= 50000000) { // 50,000 KM threshold
            // ONLY trigger if we haven't popped it up for this alert yet
            if (!_activeAlertPopups.contains(alert.alertId)) {
              print('[SOS Listener] 🚨 SYSTEM CONDITIONS MET! TRIGGERING POPUP!');
              _activeAlertPopups.add(alert.alertId);

              // 1. Show Top-Bar Local Notification (Does NOT crash on fail)
              try {
                notify.showNotification(
                  title: '🚨 NEARBY EMERGENCY',
                  body: '${alert.userName} needs help nearby! Tap to respond.',
                  payload: {
                    'alert_id': alert.alertId,
                    'type': 'emergency_dispatch',
                  },
                );
              } catch (e) {
                print('[SOS Listener] Local notification warning: $e');
              }

              // 2. Auto-Popup Responder Screen Safely
              WidgetsBinding.instance.addPostFrameCallback((_) {
                if (mounted) {
                  try {
                    print('[SOS Listener] Pushing ResponderAlertScreen onto Navigator...');
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (_) => ResponderAlertScreen(
                          alertData: {
                            'alert_id': alert.alertId,
                            'victim_name': alert.userName,
                            'lat': alert.latitude.toString(),
                            'lng': alert.longitude.toString(),
                            'type': alert.tier == 'tier1' ? 'tier1_alert' : 'tier2_alert',
                          },
                        ),
                      ),
                    ).then((_) {
                      print('[SOS Listener] ResponderAlertScreen closed.');
                    });
                  } catch (e) {
                     print('[SOS Listener] FATAL ERROR PUSHING SCREEN: $e');
                  }
                } else {
                  print('[SOS Listener] Cannot push screen: HomeDashboard is not mounted.');
                }
              });
            } else {
              print('[SOS Listener] Alert ${alert.alertId} already in popup memory. Ignoring.');
            }
          } else {
            print('[SOS Listener] Alert ${alert.alertId} is too far away. Ignored.');
          }
        }

      });

      // ── Sync FCM Token ──
      FirebaseMessaging.instance.getToken().then((token) {
        if (token != null) {
          final auth = Provider.of<AuthProvider>(context, listen: false);
          if (auth.user != null) {
            auth.updateProfile({'fcm_token': token});
            
            // Sync user ID with BackgroundService so the victim doesn't get their own SOS push
            FlutterBackgroundService().invoke('setUserId', {'id': auth.user!.id});
          }
        }
      });
    });
  }
  @override
  void dispose() {
    _sosSubscription?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.background,
      body: _screens[_currentIndex],
      bottomNavigationBar: Container(
        decoration: BoxDecoration(
          color: AppTheme.white,
          boxShadow: [
            BoxShadow(
              color: Colors.black.withAlpha(10),
              blurRadius: 20,
              offset: const Offset(0, -4),
            ),
          ],
        ),
        child: BottomNavigationBar(
          currentIndex: _currentIndex,
          onTap: (i) => setState(() => _currentIndex = i),
          items: const [
            BottomNavigationBarItem(icon: Icon(Icons.home_rounded), label: 'Home'),
            BottomNavigationBarItem(icon: Icon(Icons.map_rounded), label: 'Live Map'),
            BottomNavigationBarItem(icon: Icon(Icons.notifications_rounded), label: 'Alerts'),
            BottomNavigationBarItem(icon: Icon(Icons.person_rounded), label: 'Profile'),
          ],
        ),
      ),
    );
  }
}

class _HomeContent extends StatelessWidget {
  const _HomeContent();

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: SingleChildScrollView(
        child: Column(
          children: [
            // ── Header ──
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Row(
                    children: [
                      const Icon(Icons.info_outline, color: AppTheme.primaryBlue, size: 20),
                      const SizedBox(width: 8),
                      Text('SafeNet AI', style: AppTheme.brandText),
                    ],
                  ),
                  Container(
                    width: 40,
                    height: 40,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: AppTheme.grey100,
                    ),
                    child: const Icon(Icons.notifications_outlined, color: AppTheme.grey600, size: 22),
                  ),
                ],
              ),
            ),

            // ── Motion Detection Status ──
            Consumer<MotionDetectionService>(
              builder: (_, motion, __) => Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                  decoration: BoxDecoration(
                    color: motion.isMonitoring
                        ? (motion.dangerDetected
                            ? AppTheme.dangerRed.withAlpha(10)
                            : AppTheme.safeGreen.withAlpha(10))
                        : AppTheme.grey50,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: motion.isMonitoring
                          ? (motion.dangerDetected
                              ? AppTheme.dangerRed.withAlpha(30)
                              : AppTheme.safeGreen.withAlpha(30))
                          : AppTheme.grey200,
                    ),
                  ),
                  child: Row(
                    children: [
                      Container(
                        width: 8,
                        height: 8,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: motion.isMonitoring
                              ? (motion.dangerDetected ? AppTheme.dangerRed : AppTheme.safeGreen)
                              : AppTheme.grey400,
                        ),
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Text(
                          motion.statusText,
                          style: AppTheme.bodySmall.copyWith(
                            fontWeight: FontWeight.w600,
                            color: motion.isMonitoring
                                ? (motion.dangerDetected ? AppTheme.dangerRed : AppTheme.safeGreen)
                                : AppTheme.grey500,
                          ),
                        ),
                      ),
                      GestureDetector(
                        onTap: () {
                          if (motion.isMonitoring) {
                            motion.stopMonitoring();
                          } else {
                            motion.startMonitoring();
                          }
                        },
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                          decoration: BoxDecoration(
                            color: motion.isMonitoring ? AppTheme.grey100 : AppTheme.primaryBlue,
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: Text(
                            motion.isMonitoring ? 'OFF' : 'ON',
                            style: AppTheme.bodySmall.copyWith(
                              color: motion.isMonitoring ? AppTheme.grey600 : Colors.white,
                              fontWeight: FontWeight.w700,
                              fontSize: 11,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),

            const SizedBox(height: 12),

            // ── Audio Detection Status ──
            Consumer<AudioDetectionService>(
              builder: (_, audio, __) => Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                  decoration: BoxDecoration(
                    color: audio.isMonitoring
                        ? (audio.dangerDetected
                            ? AppTheme.dangerRed.withAlpha(10)
                            : AppTheme.primaryBlue.withAlpha(10))
                        : AppTheme.grey50,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: audio.isMonitoring
                          ? (audio.dangerDetected
                              ? AppTheme.dangerRed.withAlpha(30)
                              : AppTheme.primaryBlue.withAlpha(30))
                          : AppTheme.grey200,
                    ),
                  ),
                  child: Row(
                    children: [
                      Container(
                        width: 8,
                        height: 8,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: audio.isMonitoring
                              ? (audio.dangerDetected ? AppTheme.dangerRed : AppTheme.primaryBlue)
                              : AppTheme.grey400,
                        ),
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Text(
                          audio.isMonitoring ? '${audio.statusText} (${audio.currentDecibel.toStringAsFixed(0)}dB)' : audio.statusText,
                          style: AppTheme.bodySmall.copyWith(
                            fontWeight: FontWeight.w600,
                            color: audio.isMonitoring
                                ? (audio.dangerDetected ? AppTheme.dangerRed : AppTheme.primaryBlue)
                                : AppTheme.grey500,
                          ),
                        ),
                      ),
                      GestureDetector(
                        onTap: () {
                          if (audio.isMonitoring) {
                            audio.stopMonitoring();
                          } else {
                            audio.startMonitoring();
                          }
                        },
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                          decoration: BoxDecoration(
                            color: audio.isMonitoring ? AppTheme.grey100 : AppTheme.primaryBlue,
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: Row(
                            children: [
                              Icon(Icons.mic, size: 14, color: audio.isMonitoring ? AppTheme.grey600 : Colors.white),
                              const SizedBox(width: 4),
                              Text(
                                audio.isMonitoring ? 'OFF' : 'ON',
                                style: AppTheme.bodySmall.copyWith(
                                  color: audio.isMonitoring ? AppTheme.grey600 : Colors.white,
                                  fontWeight: FontWeight.w700,
                                  fontSize: 11,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
            const SizedBox(height: 12),

            // ── Voice Detection Status ──
            Consumer<VoiceDetectionService>(
              builder: (_, voice, __) => Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                  decoration: BoxDecoration(
                    color: voice.isMonitoring
                        ? (voice.dangerDetected
                            ? AppTheme.dangerRed.withAlpha(10)
                            : AppTheme.cautionYellow.withAlpha(10))
                        : AppTheme.grey50,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: voice.isMonitoring
                          ? (voice.dangerDetected
                              ? AppTheme.dangerRed.withAlpha(30)
                              : AppTheme.cautionYellow.withAlpha(30))
                          : AppTheme.grey200,
                    ),
                  ),
                  child: Row(
                    children: [
                      Container(
                        width: 8,
                        height: 8,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: voice.isMonitoring
                              ? (voice.dangerDetected ? AppTheme.dangerRed : AppTheme.cautionYellow)
                              : AppTheme.grey400,
                        ),
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Text(
                          voice.statusText,
                          style: AppTheme.bodySmall.copyWith(
                            fontWeight: FontWeight.w600,
                            color: voice.isMonitoring
                                ? (voice.dangerDetected ? AppTheme.dangerRed : AppTheme.cautionYellow.withAlpha(200))
                                : AppTheme.grey500,
                          ),
                        ),
                      ),
                      GestureDetector(
                        onTap: () {
                          if (voice.isMonitoring) {
                            voice.stopMonitoring();
                          } else {
                            voice.startMonitoring();
                          }
                        },
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                          decoration: BoxDecoration(
                            color: voice.isMonitoring ? AppTheme.grey100 : AppTheme.cautionYellow,
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: Row(
                            children: [
                              Icon(Icons.record_voice_over, size: 14, color: voice.isMonitoring ? AppTheme.grey600 : Colors.white),
                              const SizedBox(width: 4),
                              Text(
                                voice.isMonitoring ? 'OFF' : 'ON',
                                style: AppTheme.bodySmall.copyWith(
                                  color: voice.isMonitoring ? AppTheme.grey600 : Colors.white,
                                  fontWeight: FontWeight.w700,
                                  fontSize: 11,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),


            const SizedBox(height: 12),

            // ── Map Card ──
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20),
              child: Container(
                height: 180,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(20),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withAlpha(10),
                      blurRadius: 20,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                clipBehavior: Clip.antiAlias,
                child: Stack(
                  children: [
                    Consumer<LocationProvider>(
                      builder: (_, loc, __) => FlutterMap(
                        options: MapOptions(
                          initialCenter: LatLng(
                            loc.latitude ?? AppConstants.defaultLat,
                            loc.longitude ?? AppConstants.defaultLng,
                          ),
                          initialZoom: 14,
                          interactionOptions: const InteractionOptions(
                            flags: InteractiveFlag.none,
                          ),
                        ),
                        children: [
                          TileLayer(
                            urlTemplate: AppConstants.osmTileUrl,
                            userAgentPackageName: 'com.safenetai.safenet_ai',
                          ),
                          MarkerLayer(
                            markers: [
                              Marker(
                                point: LatLng(
                                  loc.latitude ?? AppConstants.defaultLat,
                                  loc.longitude ?? AppConstants.defaultLng,
                                ),
                                width: 50,
                                height: 50,
                                child: const Icon(
                                  Icons.location_on,
                                  color: AppTheme.dangerRed,
                                  size: 40,
                                ),
                              ),
                            ],
                          ),
                          CircleLayer(
                            circles: DangerZonesData.bangaloreZones.map((zone) {
                              final isHigh = zone.riskLevel == 'High';
                              return CircleMarker(
                                point: LatLng(zone.latitude, zone.longitude),
                                color: (isHigh ? AppTheme.dangerRed : Colors.orange).withAlpha(40),
                                borderStrokeWidth: 2,
                                borderColor: (isHigh ? AppTheme.dangerRed : Colors.orange).withAlpha(150),
                                radius: 500, // 500 meters drawn on map
                                useRadiusInMeter: true,
                              );
                            }).toList(),
                          ),
                        ],
                      ),
                    ),
                    // Location badge (Dynamic Risk Banner)
                    Positioned(
                      top: 12,
                      left: 12,
                      child: Container(
                        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                        decoration: BoxDecoration(
                          color: Provider.of<LocationProvider>(context).currentDangerZone != null 
                              ? AppTheme.dangerRed 
                              : AppTheme.safeGreen,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Container(
                              width: 8,
                              height: 8,
                              decoration: const BoxDecoration(
                                color: Colors.white,
                                shape: BoxShape.circle,
                              ),
                            ).animate(onPlay: (controller) => controller.repeat()).scale(
                                  duration: const Duration(milliseconds: 1000),
                                  begin: const Offset(1, 1),
                                  end: const Offset(1.5, 1.5),
                                  curve: Curves.easeInOut,
                                ).fade(
                                  duration: const Duration(milliseconds: 1000),
                                ),
                            const SizedBox(width: 8),
                            Text(
                              Provider.of<LocationProvider>(context).currentDangerZone != null
                                  ? 'Danger Zone: ${Provider.of<LocationProvider>(context).currentDangerZone!.area}'
                                  : 'Safe Area',
                              style: AppTheme.labelLarge.copyWith(color: Colors.white, fontSize: 12),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ).animate().fadeIn(duration: 500.ms),

            const SizedBox(height: 24),

            // ── Secured Badge ──
            Container(
              width: 64,
              height: 64,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: AppTheme.primaryBlue.withAlpha(20),
              ),
              child: const Icon(Icons.shield_rounded, color: AppTheme.primaryBlue, size: 32),
            ).animate().fadeIn(delay: 200.ms).scale(
                  begin: const Offset(0.8, 0.8),
                  end: const Offset(1.0, 1.0),
                  duration: 400.ms,
                ),
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
              decoration: BoxDecoration(
                color: AppTheme.safeGreen.withAlpha(20),
                borderRadius: BorderRadius.circular(20),
              ),
              child: Text(
                'SECURED',
                style: AppTheme.bodySmall.copyWith(
                  color: AppTheme.safeGreen,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 1.5,
                ),
              ),
            ).animate().fadeIn(delay: 300.ms),

            const SizedBox(height: 16),

            // ── Status Text ──
            Text("You're protected", style: AppTheme.headingLarge)
                .animate().fadeIn(delay: 400.ms),
            const SizedBox(height: 6),
            Text(
              'SafeNet AI is monitoring your surroundings.',
              style: AppTheme.bodyMedium,
            ).animate().fadeIn(delay: 500.ms),

            const SizedBox(height: 24),

            const SizedBox(height: 16),


            // ── Info Cards Row ──
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20),
              child: Row(
                children: [
                  Expanded(
                    child: _InfoCard(
                      icon: Icons.tips_and_updates_outlined,
                      iconColor: AppTheme.cautionYellow,
                      title: 'Safety Tip',
                      description: 'Keep your phone\'s battery above 20% for active monitoring.',
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Stack(
                      children: [
                        _InfoCard(
                          icon: Icons.warning_amber_rounded,
                          iconColor: AppTheme.dangerRed,
                          title: 'Recent Alert',
                          description: 'No active threats detected in your area.',
                        ),
                        Positioned(
                          top: 12,
                          right: 12,
                          child: Container(
                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                            decoration: BoxDecoration(
                              color: AppTheme.safeGreen,
                              borderRadius: BorderRadius.circular(10),
                            ),
                            child: Text(
                              'CLEAR',
                              style: AppTheme.bodySmall.copyWith(
                                color: Colors.white,
                                fontSize: 9,
                                fontWeight: FontWeight.w700,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ).animate().fadeIn(delay: 600.ms),

            const SizedBox(height: 16),

            // ── Danger Zone Toggle ──
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20),
              child: Consumer<LocationProvider>(
                builder: (_, loc, __) => Container(
                  padding: const EdgeInsets.all(16),
                  decoration: AppTheme.cardDecoration,
                  child: Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          color: AppTheme.cautionYellow.withAlpha(20),
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(Icons.add_alert_rounded, color: AppTheme.cautionYellow),
                      ),
                      const SizedBox(width: 14),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('Danger Zone Alerts', style: AppTheme.labelLarge),
                            Text(
                              'Notify me when entering high-crime areas',
                              style: AppTheme.bodySmall,
                            ),
                          ],
                        ),
                      ),
                      Switch(
                        value: loc.dangerZoneAlertsEnabled,
                        onChanged: (v) => loc.toggleDangerZoneAlerts(v),
                        activeColor: AppTheme.primaryBlue,
                      ),
                    ],
                  ),
                ),
              ),
            ).animate().fadeIn(delay: 620.ms),

            const SizedBox(height: 16),

            // ── Emergency Contacts Quick Access ──
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20),
              child: GestureDetector(
                onTap: () => Navigator.pushNamed(context, AppRoutes.emergencyContacts),
                child: Container(
                  width: double.infinity,
                  padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 20),
                  decoration: BoxDecoration(
                    color: AppTheme.dangerRed.withAlpha(8),
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(color: AppTheme.dangerRed.withAlpha(25)),
                  ),
                  child: Row(
                    children: [
                      Container(
                        width: 36,
                        height: 36,
                        decoration: BoxDecoration(
                          color: AppTheme.dangerRed.withAlpha(20),
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(Icons.contacts_rounded, color: AppTheme.dangerRed, size: 18),
                      ),
                      const SizedBox(width: 14),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Emergency Contacts',
                              style: AppTheme.labelLarge.copyWith(color: AppTheme.dangerRed),
                            ),
                            Text(
                              'Add family members to notify on SOS',
                              style: AppTheme.bodySmall.copyWith(fontSize: 11),
                            ),
                          ],
                        ),
                      ),
                      const Icon(Icons.chevron_right, color: AppTheme.dangerRed),
                    ],
                  ),
                ),
              ),
            ).animate().fadeIn(delay: 650.ms),

            const SizedBox(height: 12),

            // ── Simulate Danger Button ──
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20),
              child: Consumer<AgentProvider>(
                builder: (_, agent, __) => GestureDetector(
                  onTap: () => _showSimulateDialog(context, agent),
                  child: Container(
                    width: double.infinity,
                    padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 20),
                    decoration: BoxDecoration(
                      color: AppTheme.primaryBlue.withAlpha(15),
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(color: AppTheme.primaryBlue.withAlpha(40)),
                    ),
                    child: Row(
                      children: [
                        Container(
                          width: 36,
                          height: 36,
                          decoration: BoxDecoration(
                            color: AppTheme.primaryBlue.withAlpha(30),
                            shape: BoxShape.circle,
                          ),
                          child: const Icon(Icons.gps_fixed, color: AppTheme.primaryBlue, size: 18),
                        ),
                        const SizedBox(width: 14),
                        Text(
                          'Simulate Danger',
                          style: AppTheme.labelLarge.copyWith(color: AppTheme.primaryBlue),
                        ),
                        const Spacer(),
                        const Icon(Icons.chevron_right, color: AppTheme.primaryBlue),
                      ],
                    ),
                  ),
                ),
              ),
            ).animate().fadeIn(delay: 700.ms),

            const SizedBox(height: 16),

            // ── SOS Button ──
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20),
              child: Consumer<AgentProvider>(
                builder: (_, agent, __) => GestureDetector(
                  onLongPress: () => _triggerSOS(context, agent),
                  child: Container(
                    width: double.infinity,
                    padding: const EdgeInsets.symmetric(vertical: 20),
                    decoration: BoxDecoration(
                      gradient: AppTheme.dangerGradient,
                      borderRadius: BorderRadius.circular(18),
                      boxShadow: [
                        BoxShadow(
                          color: AppTheme.dangerRed.withAlpha(60),
                          blurRadius: 20,
                          offset: const Offset(0, 8),
                        ),
                      ],
                    ),
                    child: Column(
                      children: [
                        Text(
                          'SOS',
                          style: AppTheme.displayLarge.copyWith(
                            color: Colors.white,
                            fontSize: 32,
                            fontWeight: FontWeight.w900,
                          ),
                        ),
                        Text(
                          'HOLD TO TRIGGER EMERGENCY',
                          style: AppTheme.bodySmall.copyWith(
                            color: Colors.white.withAlpha(200),
                            fontSize: 11,
                            letterSpacing: 1.5,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ).animate().fadeIn(delay: 800.ms).scale(
                  begin: const Offset(0.95, 0.95),
                  end: const Offset(1.0, 1.0),
                  duration: 400.ms,
                ),

            const SizedBox(height: 24),
          ],
        ),
      ),
    );
  }

  void _showSimulateDialog(BuildContext context, AgentProvider agent) {
    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: Row(
          children: [
            const Icon(Icons.warning_amber_rounded, color: AppTheme.cautionYellow),
            const SizedBox(width: 10),
            const Text('Simulate Danger'),
          ],
        ),
        content: const Text(
          'This will simulate the AI agent pipeline:\n\n'
          '1. Detection Agent → Analyze sensors\n'
          '2. Context Agent → Check location risk\n'
          '3. Decision Agent → Calculate risk score\n'
          '4. Response Agent → Dispatch alerts\n\n'
          'No real emergency will be triggered.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () {
              Navigator.pop(context);
              _runSimulation(context, agent);
            },
            style: ElevatedButton.styleFrom(backgroundColor: AppTheme.dangerRed),
            child: const Text('Simulate', style: TextStyle(color: Colors.white)),
          ),
        ],
      ),
    );
  }

  void _triggerSOS(BuildContext context, AgentProvider agent) {
    _runSimulation(context, agent);
  }

  void _runSimulation(BuildContext context, AgentProvider agent) {
    final auth = Provider.of<AuthProvider>(context, listen: false);
    final loc = Provider.of<LocationProvider>(context, listen: false);
    final user = auth.user ?? UserModel(id: 'demo', name: 'Demo User', phone: '', email: '');
    agent.runDangerSimulation(
      user: user,
      latitude: loc.latitude ?? AppConstants.defaultLat,
      longitude: loc.longitude ?? AppConstants.defaultLng,
    );
    _showAgentProgress(context, agent);
  }

  void _showAgentProgress(BuildContext context, AgentProvider agent) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      builder: (_) => DraggableScrollableSheet(
        initialChildSize: 0.6,
        minChildSize: 0.3,
        maxChildSize: 0.9,
        expand: false,
        builder: (_, controller) => Consumer<AgentProvider>(
          builder: (_, ag, __) => Container(
            padding: const EdgeInsets.all(24),
            child: ListView(
              controller: controller,
              children: [
                Center(
                  child: Container(
                    width: 40,
                    height: 4,
                    decoration: BoxDecoration(
                      color: AppTheme.grey300,
                      borderRadius: BorderRadius.circular(2),
                    ),
                  ),
                ),
                const SizedBox(height: 20),
                Text('Agent Pipeline', style: AppTheme.headingMedium),
                const SizedBox(height: 4),
                Text('Multi-agent risk analysis', style: AppTheme.bodyMedium),
                const SizedBox(height: 20),
                ...ag.agentLog.map((log) => Padding(
                      padding: const EdgeInsets.only(bottom: 12),
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Icon(
                            log.contains('✅')
                                ? Icons.check_circle
                                : log.contains('🔵')
                                    ? Icons.play_circle_fill
                                    : Icons.circle,
                            color: log.contains('✅')
                                ? AppTheme.safeGreen
                                : AppTheme.primaryBlue,
                            size: 20,
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Text(log, style: AppTheme.bodyMedium),
                          ),
                        ],
                      ),
                    )),
                if (ag.isProcessing)
                  const Center(child: CircularProgressIndicator(color: AppTheme.primaryBlue)),
                if (!ag.isProcessing && ag.agentLog.isNotEmpty) ...[
                  const SizedBox(height: 16),
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton(
                      onPressed: () => Navigator.pop(context),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppTheme.safeGreen,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                      ),
                      child: const Text('✅ Mark as Resolved', style: TextStyle(color: Colors.white)),
                    ),
                  ),
                ],
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _InfoCard extends StatelessWidget {
  final IconData icon;
  final Color iconColor;
  final String title;
  final String description;

  const _InfoCard({
    required this.icon,
    required this.iconColor,
    required this.title,
    required this.description,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: AppTheme.cardDecoration,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, color: iconColor, size: 22),
          const SizedBox(height: 10),
          Text(title, style: AppTheme.labelLarge),
          const SizedBox(height: 4),
          Text(
            description,
            style: AppTheme.bodySmall.copyWith(fontSize: 11, height: 1.4),
            maxLines: 3,
            overflow: TextOverflow.ellipsis,
          ),
        ],
      ),
    );
  }
}
